# 版本锁定约定（ADR-0006）：两平台必须锁定同一 Minecraft 版本。
minecraftVersion=1.21.1
# NeoForge 版本（对应 MC 1.21.1）
neoForgeVersion=21.1.183
# Fabric Loom 版本
loomVersion=1.17.19

modVersion=0.1.0
mavenGroup=top.tangge233

# 国内网络镜像：Gradle distribution 使用腾讯云。
distributionUrl=https\://mirrors.cloud.tencent.com/gradle/gradle-9.7.1-bin.zip
systemProp.maven.repo1=maven.aliyun.com/repository/public
