pluginManagement {
    repositories {
        maven { url = 'https://maven.aliyun.com/repository/public' }
        maven { url = 'https://maven.fabricmc.net' }
        maven { url = 'https://maven.neoforged.net' }
        gradlePluginPortal()
    }
}

rootProject.name = 'net-bridge'

include 'common'
include 'neoforge'
include 'fabric'
