[package]
name = "net-bridge-native"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"

[lib]
name = "net_bridge_native"
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"

[dependencies]
# Runtime
jni = "0.22"
tokio = { version = "1", features = ["full"] }
thiserror = "2"

# Record
dashmap = "6"

# Connection
socket2 = "0.6"

quinn = { version = "0.11", default-features = false, features = ["runtime-tokio", "rustls-ring"] }
quinn-proto = "0.11"
quinn-plaintext = "0.3"
bytes = "1"

fec = "0.2.2"
kcp-rs = "0.2.6"
smux = "0.2"

[profile.release]
opt-level = 3
lto = true
strip = "symbols"
